SEARCH_RESULTS_COUNT = 10
CHUNK_SIZE = 500
CHUNK_OVERLAP = 50
TOP_K_CHUNKS = 3
TOP_K_URLS = 5
MAX_TEXT_LENGTH = 10000


EMBEDDING_MODEL = "all-MiniLM-L6-v2"
LLM_MODEL = "hf.co/unsloth/gemma-3n-E4B-it-GGUF:UD-Q4_K_XL"


HEADLESS_BROWSER = True
WAIT_TIMEOUT = 15